import { initializeApp } from "firebase/app"
import { getFirestore, doc, setDoc } from "firebase/firestore";

const firebaseConfig = {
  apiKey: "AIzaSyBTTNgZrChp9aZ6fQA8GP2BFA_6jlM1L0c",
  authDomain: "river-b7f8d.firebaseapp.com",
  projectId: "river-b7f8d",
  storageBucket: "river-b7f8d.firebasestorage.app",
  messagingSenderId: "723403321780",
  appId: "1:723403321780:web:c281758878acd63d9882e1",
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

const users = [
  {
    uid: "u1",
    name: "Alice Johnson",
    email: "alice@example.com",
    role: "admin",
    status: "active",
    balance: "$50,000",
    kycVerified: true,
    lastLogin: "1 hour ago",
    lastFunded: "2025-11-30",
    transactions: 120,
    walletAddress: "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa",
    createdAt: "2025-01-15",
  },
  {
    uid: "u2",
    name: "Bob Smith",
    email: "bob@example.com",
    role: "user",
    status: "active",
    balance: "$12,450",
    kycVerified: true,
    lastLogin: "2 hours ago",
    lastFunded: "2025-11-29",
    transactions: 45,
    walletAddress: "3J98t1WpEZ73CNmQviecrnyiWrnqRhWNLy",
    createdAt: "2025-02-12",
  },
  {
    uid: "u3",
    name: "Charlie Brown",
    email: "charlie@example.com",
    role: "user",
    status: "inactive",
    balance: "$3,200",
    kycVerified: false,
    lastLogin: "1 week ago",
    lastFunded: "2025-10-15",
    transactions: 10,
    walletAddress: "1BoatSLRHtKNngkdXEeobR76b53LETtpyT",
    createdAt: "2025-03-01",
  },
  {
    uid: "u4",
    name: "David Lee",
    email: "david@example.com",
    role: "user",
    status: "active",
    balance: "$7,500",
    kycVerified: true,
    lastLogin: "5 hours ago",
    lastFunded: "2025-11-28",
    transactions: 25,
    walletAddress: "1QLbGuc3WGpVt7p4Y3rMEGJrHfNqTi9RtC",
    createdAt: "2025-04-12",
  },
  {
    uid: "u5",
    name: "Eva Green",
    email: "eva@example.com",
    role: "user",
    status: "active",
    balance: "$15,800",
    kycVerified: true,
    lastLogin: "2 days ago",
    lastFunded: "2025-11-25",
    transactions: 50,
    walletAddress: "3FZbgi29cpjq2GjdwV8eyHuJJnkLtktZc5",
    createdAt: "2025-05-05",
  },
  {
    uid: "u6",
    name: "Frank Miller",
    email: "frank@example.com",
    role: "user",
    status: "inactive",
    balance: "$900",
    kycVerified: false,
    lastLogin: "2 weeks ago",
    lastFunded: "2025-10-10",
    transactions: 5,
    walletAddress: "1FfmbHfnpaZjKFvyi1okTjJJusN455paPH",
    createdAt: "2025-06-15",
  },
  {
    uid: "u7",
    name: "Grace Hopper",
    email: "grace@example.com",
    role: "user",
    status: "active",
    balance: "$23,400",
    kycVerified: true,
    lastLogin: "3 hours ago",
    lastFunded: "2025-11-30",
    transactions: 80,
    walletAddress: "1dice8EMZmqKvrGE4Qc9bUFf9PX3xaYDp",
    createdAt: "2025-07-21",
  },
  {
    uid: "u8",
    name: "Henry Adams",
    email: "henry@example.com",
    role: "user",
    status: "active",
    balance: "$5,600",
    kycVerified: true,
    lastLogin: "4 hours ago",
    lastFunded: "2025-11-29",
    transactions: 20,
    walletAddress: "3QJmV3qfvL9SuYo34YihAf3sRCW3qSinyC",
    createdAt: "2025-08-03",
  },
  {
    uid: "u9",
    name: "Isla Fisher",
    email: "isla@example.com",
    role: "user",
    status: "active",
    balance: "$9,750",
    kycVerified: false,
    lastLogin: "1 day ago",
    lastFunded: "2025-11-27",
    transactions: 30,
    walletAddress: "1P5ZEDWTKTFGxQjZphgWPQUpe554WKDfHQ",
    createdAt: "2025-09-12",
  },
  {
    uid: "u10",
    name: "Jack Black",
    email: "jack@example.com",
    role: "user",
    status: "active",
    balance: "$11,200",
    kycVerified: true,
    lastLogin: "6 hours ago",
    lastFunded: "2025-11-30",
    transactions: 35,
    walletAddress: "3Cbq7aT1tY8kMxWLbitaG7y3b5J7mR2j4",
    createdAt: "2025-10-20",
  },
];

async function seedUsers() {
  for (const user of users) {
    await setDoc(doc(db, "users", user.uid), user);
    console.log(`Added ${user.name}`);
  }
}

seedUsers().then(() => console.log("All users added!"));
